### DISCUSSION TITLE
Wrong driver version

### DISCUSSION THREAD

**Discussion by ludys1** [atata-framework/atata-webdriversetup#6] [Q&A]
Hi Yevgeniy!

We are using your framework in a project and the day before yesterday our tests started to failing. We are bulding our tests through github actions the build is succesfull but all tests are failing because of the wrong chrome version as far as I understand the error message below:

A total of 1 test files matched the specified pattern.
Starting ChromeDriver 92.0.4515.43 (8c61b7e2989f2990d42f859cac71319137787cce-refs/branch-heads/4515@{#306}) on port 36785
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
  X BE_UserWantsToCreateANewBusinessUnit [871ms]
  Error Message:
   System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 92
Current browser version is 91.0.4472.164 with binary path /usr/bin/google-chrome (SessionNotCreated)

Locally the tests are working as I have the latest chrome version but when running on the server with such configuration its not working:

```yaml
name: Tests Run
on: 
  workflow_dispatch:
  repository_dispatch:
    types: [be_deployed, fe_deployed]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x']

    steps:
    - name: 'Checkout iFLOW.testing'
      uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --logger:"nunit;LogFilePath=Reports/test-result.xml" --no-build --no-restore
      continue-on-error: true
    - name: Get Xray Cloud API token
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      id: xray-token
      run: |
        echo ::set-output name=XRAY_TOKEN::$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"$CLIENT_ID\",\"client_secret\": \"$CLIENT_SECRET\" }" https://xray.cloud.xpand-it.com/api/v2/authenticate| tr -d '"')
    - name: Submit results to Xray
      run: 'curl -H "Content-Type: text/xml" -H "Authorization: Bearer ${{ steps.xray-token.outputs.XRAY_TOKEN }}" --data @/home/runner/work/IFLOW.testing/IFLOW.testing/Reports/test-result.xml  "https://xray.cloud.xpand-it.com/api/v2/import/execution/nunit?projectKey=IB"'
```

there is no chrome configuration so I guess the version needs to come somewhere from atata config, but I dont have any specific version choosed anywhere:

config:

```cs
AtataContext.GlobalConfiguration
    .UseChrome()
    .WithArguments("start-maximized")
    .UseCulture("en-US")
    .UseAllNUnitFeatures()
    .ApplyJsonConfig<AtataConfig>();
```

atata.json:

```json
{
  "drivers": [
    {
      "type": "chrome",
      "alias": "chrome",
      "options": {
        "arguments": [ "start-maximized" ]
      }
    },
    {
      "type": "chrome",
      "alias": "chrome-headless",
      "options": {
        "arguments": [ "headless", "window-size=1920,1080" ]
      }
    }
  ],
  "baseUrl": "",
  "culture": "en-US",
  "useAllNUnitFeatures": true
}
```

Can you help me to resolve this problem? 
Greetings from Poland, 
Filip.
